### ISSUE TITLE
scriptable 看不到脚本

### ISSUE THREAD

**Issue by Composure17** [Vxider/NiuDataWidget#11]
scriptable 看不到脚本 打开里面全是空的 您又出现这个问题吗

**Comment by Vxider** [comment]
需要手动下载脚本，拷贝到scriptable目录就行

**Comment by Composure17** [comment]
![image](https://user-images.githubusercontent.com/38198174/209088870-dd6106d5-3a18-4ccf-ad0d-1d38dcab2088.png)
我本来已经在用着的 这几天不知道咋回事

**Comment by Vxider** [comment]
是不是icloud同步的问题

**Comment by Composure17** [comment]
好像还真是 打开文件看到icloud看不到 重启了好几次才行
