### ISSUE TITLE
widget的小地图显示空白！

### ISSUE THREAD

**Issue by otherbanana** [Vxider/NiuDataWidget#12]
如图
<img width="329" alt="image" src="https://user-images.githubusercontent.com/34509569/213958486-10f1bd95-a08c-4145-b619-c2e64d916faa.png">

但是地图位置如需显示最近旅程则能正确显示。

**Comment by otherbanana** [comment]
就是车辆位置无法显示出来

**Comment by Vxider** [comment]
是不是网络问题
