### ISSUE TITLE
反复多次调试均无法显示地图 只有一个地址

### ISSUE THREAD

**Issue by ClayMoreBoy** [Vxider/NiuDataWidget#3]
车型：小牛u+
地图数据已经获取
niu_last_track_xxx.dat

**Comment by Vxider** [comment]
需要正确设置变量
```
var show_last_track_map = true
var hide_map = true
```
地图下载成功后，会有缓存文件`niu_last_track_thumb_token.png`

**Comment by ClayMoreBoy** [comment]
这个可以  现在只出现“敬告”盾牌 没出现“开关”按钮

**Comment by Vxider** [comment]
> 没出现“开关”按钮

开关是指`screen_003`里的小牛操作开关吗，操作开关需要手动在快捷指令里面导入

**Comment by ClayMoreBoy** [comment]
已导入快捷指令 怎么在盾牌的左边加入开关图标(起指向快捷指令作用的)

**Comment by Vxider** [comment]
我没太明白你的意思，是想要在scriptable小组件内部实现目前快捷指令所实现的这几个功能，而不使用快捷指令？ 其实快捷指令就是调用了scriptable脚本

**Comment by ClayMoreBoy** [comment]
1 盾牌旁边没图标 无法按 就是想小组件内实现4个快捷指令 
2 另外黑暗模式不灵活 要小修改代码实现重新覆盖
3 地图能用百度的黑暗(晚上) 白色(白天)缩略图？
4 2️⃣3️⃣同时更新

**Comment by Vxider** [comment]
> 就是想小组件内实现4个快捷指令

快捷指令可以后台运行（点按后不会打开app），可以锁屏运行，据我了解其他的app里不太容易实现。

> 黑暗模式不灵活

可否详细说明，是不希望跟随系统，想要手动设定吗

**Comment by ClayMoreBoy** [comment]
> > 就是想小组件内实现4个快捷指令
> 
> 快捷指令可以后台运行（点按后不会打开app），可以锁屏运行，据我了解其他的app里不太容易实现。
没图标按不了
> 
> > 黑暗模式不灵活
> 
> 可否详细说明，是不希望跟随系统，想要手动设定吗
跟随系统

**Comment by Vxider** [comment]
目前就是跟随系统

**Comment by ClayMoreBoy** [comment]
> 目前就是跟随系统

到晚上也没换黑色 微信都变色了

**Comment by Vxider** [comment]
需要等小组件重新更新运行，才能改变颜色，系统切换主题时并不会自动触发小组件运行。可以手动切换系统主题，然后在scriptable里测试是否变色

**Comment by ClayMoreBoy** [comment]
> 需要等小组件重新更新运行，才能改变颜色，系统切换主题时并不会自动触发小组件运行。可以手动切换系统主题，然后在scriptable里测试是否变色

如果这样的话能否添加代码触发restart小组件

**Comment by Vxider** [comment]
应该不行

**Comment by ClayMoreBoy** [comment]
> 应该不行

不行的那只有 在盾牌左边显示开关图标
地图别用苹果 用百度的白天黑夜模式地图

**Comment by Vxider** [comment]
界面只有scriptable主动刷新才能变。可以向scriptable提出更好刷新方案的建议，比如系统外观切换时自动刷新。

至于小组件内部增加开关按钮，前面提到了，由于按钮无法实现后台运行，点击后只能打开APP才可以实现开关操作，所以我认为不如快捷指令方便。

**Comment by ClayMoreBoy** [comment]
> 界面只有scriptable主动刷新才能变。可以向scriptable提出更好刷新方案的建议，比如系统外观切换时自动刷新。
> 
> 至于小组件内部增加开关按钮，前面提到了，由于按钮无法实现后台运行，点击后只能打开APP才可以实现开关操作，所以我认为不如快捷指令方便。

那也是 现在就想换个百度地图的api 加个key申清地址(免费的好像是每天1万次查询)

**Comment by Vxider** [comment]
目前的地图是支持黑色模式的，只不过由于地图缓存，同一张缓存图片不会重复下载，所以地图无法自动切换

**Comment by Vxider** [comment]
已更新代码，目前会同时缓存黑色主题和白天主题地图，需要手动删除icloud中的旧缓存图片。

**Comment by ClayMoreBoy** [comment]
能否用小牛app里的那个定位图？
电池延保 电池信息 上面的左地址 右地图 我看dat有相关信息

**Comment by Vxider** [comment]
目前定位图默认用苹果地图，上次骑行线路图用小牛地图。电池信息考虑到界面整洁度，可以自己在scriptable中添加。

**Comment by ClayMoreBoy** [comment]
> 目前定位图默认用苹果地图，上次骑行线路图用小牛地图。电池信息考虑到界面整洁度，可以自己在scriptable中添加。

![Uploading EA9F438C-86FD-43D2-B6E5-E5F85EE62A47.jpeg…]()
