### ISSUE TITLE
关于一些请求的问题

### ISSUE THREAD

**Issue by Composure17** [Vxider/NiuDataWidget#7]
大佬你好 我想问一下登陆那儿是个post请求 那我怎么知道他要传哪些值才能拿到返回的data呢

**Comment by Composure17** [comment]
如果获取了电池信息 该怎么显示上去呢

**Comment by Vxider** [comment]
> 如果获取了电池信息 该怎么显示上去呢

现在就有电池信息显示呀

**Comment by Vxider** [comment]
> 大佬你好 我想问一下登陆那儿是个post请求 那我怎么知道他要传哪些值才能拿到返回的data呢

可以通过手机的一些软件抓包看看

**Comment by Composure17** [comment]
已经抓到一些了 比如说总里程什么的 如果不用快捷指令 有没有可能在小组件上能搞个按钮实现解锁开机的操作 我的好像关闭那个快捷指令没反应

**Comment by Vxider** [comment]
我这边快捷指令可以使用，建议调试下看什么问题，当时使用快捷指令主要考虑以下几点：
1. scriptable不支持button（最新版本不确定是否支持）
2. scriptable点击后会跳转至app，而快捷指令不会
3. 快捷指令可以不解锁手机操作

**Comment by Composure17** [comment]
就是如果要button 就耀去Objective-C了？

**Comment by Vxider** [comment]
抱歉我并不是很了解，如果您看到有其他类似app的widget支持button，可以一起研究下

**Comment by Composure17** [comment]
我看到一个 app store叫数据板 如果你有小红书你可以搜一下 小牛小组件 他那个是收费的

**Comment by Vxider** [comment]
付费的就不考虑了

**Comment by Composure17** [comment]
小红书上能看到个大概 感觉像是你的这个美化版 而且开发成了app

**Comment by Vxider** [comment]
看了下，我不太喜欢比较花哨的风格。另外“数据板”上的解锁按钮有点小，感觉还是快捷指令方便

**Comment by DoubleDimples** [comment]
不好意思小白提问username是填写邮箱号吗，一直显示账号密码不正确TAT

**Comment by Composure17** [comment]
> 不好意思小白提问username是填写邮箱号吗，一直显示账号密码不正确TAT

邮箱手机号 密码是加密过之后的密码

**Comment by yaojiajian** [comment]
大神，想问一下我的小组件右边就是出不来地图怎么解呢
