### ISSUE TITLE
您好，感谢您的教学，想问一下为啥我的小组件左边的地图一直显示不出来呢

### ISSUE THREAD

**Issue by yaojiajian** [Vxider/NiuDataWidget#9]
去注册地图的API key又注册失败，company那一栏不知道写什么。一直显示验证失败

**Comment by Vxider** [comment]
可以通过如下设置使用苹果地图，不需要注册地图API

https://github.com/Vxider/NiuDataWidget/blob/ec759652ebb6e47e71fbd6f3d30fc0cd055ad84c/NiuDataWidget.js#L22

**Comment by Vxider** [comment]
文档已更新，参照如下设置试一下
```javascript
var show_last_track_map = false
var show_map = true
```

另外 MAP API 可以先不申请，使用内置的测试通过后再申请

**Comment by yaojiajian** [comment]
还是不行诶，其他都没有问题就是地图出不来
![Uploading 9F058921-B587-41F2-AB70-E05223CC7BEF.jpeg…]()

**Comment by Vxider** [comment]
图片挂了，可以调试一下看`mapImage`是否获取成功，或者改一个临时密码，然后把脚本发我邮箱，我可以帮忙看下是否配置有问题。

**Comment by yaojiajian** [comment]
感谢，您邮箱多少呢。我发您看一下

**Comment by Vxider** [comment]
lb@vxider.com

**Comment by Vxider** [comment]
已解决
